### PR TITLE
July 2nd, 3rd, 4th, and 5th+ schedules

### PR DESCRIPTION
**Pull request by thegreengrass**

### CODE REVIEW

**Comment by flibbertigibbet** [comment]
Thanks for the PR!  Some formatting notes:
* fields should be quoted
* no spaces within fields
* the weird stuff that comes through for skipped stations should be replaced with `&gt;` (see old files)

Sometimes skipped stations on express lines come through as empty fields, sometimes some variation on hyphens and backticks.  Not sure what that's about, but I just replace them all with `&gt;`, for consistency.

**Comment by thegreengrass** [comment]
I went through and did all of these, take a look!

**Comment by flibbertigibbet** [comment]
Great, thanks!

I'm going to create a new PR that excludes the first three commits from this (a PR should start from the current master state).

If you'd like to incorporate a special Christmas schedule, please open that on a separate PR.  It would be good to find a way to build that without duplicating all the trips/stops builder logic.  Also, what is the source for the Christmas special schedule?

**Comment by flibbertigibbet** [comment]
Closing in favor of #11.  Thanks again @thegreengrass!

**Pull request closed without merging**
